#!/bin/sh

APATH=$1
NM=`basename "$1"`

SE=$APATH/$NM.se

[ -d "$APATH" ] || exit 1
shift ; eval $*

sexp=

# Version:1
Ver=$Version
if [ "$Ver" = + ]; then
    Ver=`grep '^Version:' $SE |awk -F: '{print $2+1}'`
fi
if [ -n "$Ver" ]; then
    sexp="$sexp -e /^Version:/s/:.*/:$Ver/"
fi

# Endian:0
if [ -n "$Endian" ]; then
    sexp="$sexp -e /^Endian:/s/:.*/:$Endian/"
fi

# Screen:240x320,240x400,320x480,220x176
if [ -n "$Screen" ]; then
    sexp="$sexp -e /^Screen:/s/:.*/:$Screen/"
    s=`echo $Screen |cut -d, -f1`
    # cp -vt $APATH $APATH/Resource/$s/*.re
	# echo sh $APATH/Resource/resinit.sh $s/normal
	# echo sh $APATH/Resource/resinit.sh $s/wides
fi

# Files:kitpay.c,kitdo.c,httpc.c,utility.c,llapi.c
if [ -n "$Files" ]; then
    sexp="$sexp -e /^Files:/s/:.*/:$Files/"
else
    Files=`/bin/ls -m *.c |tr -d ' '`
    sexp="$sexp -e /^Files:/s/:.*/:$Files/"
fi

if [ -n "$sexp" ]; then
    sed $sexp <&0 > $SE
    which unix2dos && unix2dos -q $SE ; true
fi

