#!/bin/sh

[ -d "$1" ] || exit 1
indir="$1" ; shift

GPG_OPTS="--quiet --yes --batch"

find "$indir" -type f | while read fn; do
    #echo gpg -e -o "$fn.gpg" $GPG_OPTS $* "$fn && rm -f $fn"
    gpg -e -o "$fn.gpg" $GPG_OPTS $* "$fn" && rm -f "$fn"
done

