#!/bin/sh
# $ eval $(gpg-agent --daemon)

[ -d "$1" ] || exit 1
indir="$1"
#indir="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

GPG_OPTS="--quiet --yes --batch"

cwd="`pwd`"

cd "$indir"
find * -name '*.gpg' | sed 's/\.gpg$//' | while read gpgfile; do
    out="$cwd/Copy/`basename "$indir"`/$gpgfile"
    d=`dirname "$out"`
    [ -d "$d" ] || mkdir -p $d || exit 2

    # echo "gpg2 -d $GPG_OPTS $indir/$gpgfile.gpg > $out"
    echo gpg2 -d $GPG_OPTS "$cwd/$indir/$gpgfile.gpg > $out"
    gpg2 -d $GPG_OPTS "$cwd/$indir/$gpgfile.gpg" > "$out"
    # gpg2 -d $GPG_OPTS "$gpgfile" | gpg2 -e -r "$gpg_id" -o "$gpgfile.new" $GPG_OPTS
done
cd "$cwd"

