#!/bin/sh

trac=$1
afile=$2
host=${3:-$HOST}
port=${4:-8000}

imsi=${IMSI:-460028118651432}
sn=${SN:-11}

if [ $# -lt 2 -o ! -f "$afile" ]; then
    exit 1
fi
echo $trac $afile $host $port

fsize=`stat -c "%s" $afile`

# echo -ne "POST http://$HOST:8000/ig/chs HTTP/1.1\r\n"
# echo -ne "Content-Type: application/octet-stream\r\n"
# echo -ne "User-Agent: NokiaN73-1/4.0727.2.4.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1\r\n"
# echo -ne "Cookie: cj=100/$trac/$trac; ci=1000011/1000012/1000013\r\n"
# echo -ne "Content-Length: $clen\r\n"
# echo -ne "\r\n"
# 
# cat $afile

# POST /ig/chs HTTP/1.1
# Host: $HOST:8000
# Content-Type: application/octet-stream
# Cookie: cj=685322241/0/0; ci=357470005665264/460029194251377/+8613800755500
# Content-Length: 1023
# Via: WTP/1.1 GDGZ-PB-GW018-WAP22 (Nokia WAP Gateway 4.1 CD1/ECD13_E/4.1.05)
# X-Forwarded-For: 10.66.0.247
# X-Source-ID: SZHGGSN403BNk
# X-Nokia-CONNECTION_MODE: TCP
# X-Up-Bearer-Type: GPRS
# X-Nokia-gateway-id: NWG/4.1/Build4.1.05
# x-up-bear-type: GPRS/EDGE
# accept: */*

cmd=Ch-Response
if [ $trac = 0 ]; then
    cmd=Ch-Init
fi

echo -ne "Ch-Variables IMEI=357470005665264 IMSI=$imsi SMSC=+8613800755500\r\n\r\n \r\n" >/tmp/chp
echo -ne "$cmd trac=$trac size=$fsize\r\n" >>/tmp/chp
cat $afile >>/tmp/chp
echo -ne "Ch-Variables IMEI=357470005665264 IMSI=$imsi SMSC=+8613800755500\r\n" >>/tmp/chp

clen=`stat -c "%s" /tmp/chp`

echo -ne "POST /ig/chs HTTP/1.1\r\n"\
"Host: $HOST:8000\r\n"\
"Content-Type: application/octet-stream\r\n"\
"Cookie: ck=$imsi\r\n"\
"Content-Length: $clen\r\n"\
"accept: */*\r\n"\
"\r\n" | cat - /tmp/chp |nc $host $port

